# Arquivo: src/main/resources/application-prod.yml
spring:
  datasource:
    url: jdbc:postgresql://${PGHOST:${DB_HOST:postgres}}:${PGPORT:${DB_PORT:5432}}/${PGDATABASE:${POSTGRES_DB}}
    username: ${PGUSER:${POSTGRES_USER}}
    password: ${PGPASSWORD:${POSTGRES_PASSWORD}}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  docker:
    compose:
      enabled: false # Em produção, a orquestração é externa

logging:
  level:
    root: INFO
    br.com.dht.apibackend: INFO
